# Generated by Django 3.1.7 on 2021-03-05 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Номер должен быть в формате: '+996 999 999 999'. До 14 символов.", regex='^\\+?1?\\d{9,14}$')])),
                ('address', models.CharField(max_length=500)),
                ('tin', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Номер должен быть в формате: '+996 999 999 999'. До 14 символов.", regex='^\\+?1?\\d{9,14}$')])),
            ],
        ),
    ]
