# Generated by Django 3.1.7 on 2021-03-05 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Номер Телефона должен быть в формате: '0555111333'. 10 символов.", regex='^\\+?1?\\d{10,10}$')])),
                ('address', models.CharField(max_length=500)),
                ('tin', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message="Номер ИНН должен быть в формате: '12345678901234'. 14 символов.", regex='^\\+?1?\\d{14,14}$')])),
            ],
        ),
    ]
