# Generated by Django 3.1.7 on 2021-03-05 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Номер Телефона должен быть в формате: '996123456789'. 12 символов.", regex='^\\+?1?\\d{12,12}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tin',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Номер ИНН должен быть в формате: '12345678901234'. 14 символов.", regex='^\\+?1?\\d{14,14}$')]),
        ),
    ]
