# Generated by Django 3.1.7 on 2021-03-05 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20210305_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Номер Телефона должен быть в формате: '0555111333'. 10 символов.", regex='^\\+?1?\\d{10,10}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tin',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message="Номер ИНН должен быть в формате: '12345678901234'. 14 символов.", regex='^\\+?1?\\d{14,14}$')]),
        ),
    ]
